<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Template for displaying new products widget
 *
 * @var $block \Magento\Catalog\Block\Product\Widget\NewWidget
 */
if ($exist = ($block->getProductCollection() && $block->getProductCollection()->getSize())) {
    $type = 'widget-new-grid';

    $mode = 'grid';

    $image = 'new_products_content_widget_grid';
    $title = __('Our Babywear Range – Beautiful, wearable, comfortable');
    $items = $block->getProductCollection()->getItems();

    $showWishlist = true;
    $showCompare = true;
    $showCart = true;
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::DEFAULT_VIEW;
    $description = true;
}
?>

<?php if ($exist):?>
    <div class="block widget block-new-products <?php /* @escapeNotVerified */ echo $mode; ?>">
        <div class="container">
            <div class="block-title">
                <strong role="heading" aria-level="2"><?php /* @escapeNotVerified */
                    echo $title; ?></strong>
            </div>
            <div class="block-content product-showcasing-slider">
                <?php /* @escapeNotVerified */
                echo '<!-- ' . $image . '-->' ?>
                <div class="products-<?php /* @escapeNotVerified */
                echo $mode; ?> <?php /* @escapeNotVerified */
                echo $mode; ?>">
                    <ol class="product-items <?php /* @escapeNotVerified */
                    echo $type; ?>">
                        <?php $iterator = 1; ?>
                        <?php foreach ($items as $_item): ?>
                            <?php /* @escapeNotVerified */
                            echo ($iterator++ == 1) ? '<li class="product-item">' : '</li><li class="product-item">' ?>
                            <div class="product-item-info">
                                <a href="<?php /* @escapeNotVerified */
                                echo $block->getProductUrl($_item) ?>" class="product-item-photo">
                                    <?php echo $block->getImage($_item, $image)->toHtml(); ?>
                                </a>
                                <div class="product-item-details">
									<div class="detailsCont">
										<div class="detailsInner">
					<?php $_objectManager = \Magento\Framework\App\ObjectManager::getInstance(); ?>
                        <?php     $cats = $_item->getCategoryIds();
                                if(count($cats) ){

                                    if($cats[0]==2){
                                        $firstCategoryId = $cats[1];
                                    }
                                    else{
                                          $firstCategoryId = $cats[0];
                                    }

                            $_category = $_objectManager->create('Magento\Catalog\Model\Category')->load($firstCategoryId);
                            $categorykey = $_category->getUrlKey();
                            $siteurl= $block->getUrl('*/*/*', ['_current' => true, '_use_rewrite' => true]);      
                            $pro_url=$siteurl.$categorykey."/".$_item->getUrlKey().".html";
                            }
                            else{
                                $pro_url=$block->getProductUrl($_item);
                            }
                     ?>
					<strong class="product-item-name">
						<a title="<?php echo $block->escapeHtml($_item->getName()) ?>"
						   href="<?php 
						   echo $pro_url; //$block->getProductUrl($_item) ?>"
						   class="product-item-link">
							<?php echo $block->escapeHtml($_item->getName()) ?>
						</a>
					</strong>
											<p class="product-small-desc">
												<?php $data = $_item->getDescription();
												$pos=strpos($data, ' ', 50);
												echo substr($data,0,$pos ); 
                                                //echo implode(' ', array_slice(str_word_count($data, 2), 0, 5));
                                                ?>
											</p>

											<?php echo $block->getProductPriceHtml($_item, $type);  ?>

											<?php if ($templateType): ?>
												<?php echo $block->getReviewsSummaryHtml($_item, $templateType) ?>
											<?php endif; ?>

											<a href="<?php echo $pro_url;//$block->getProductUrl($_item) ?>" class="shopNowBtn lined">Shop Now</a>
										</div>
									</div>
                                </div>
                            </div>
                            <?php echo ($iterator == count($items) + 1) ? '</li>' : '' ?>
                        <?php endforeach ?>
                    </ol>
                </div>
                <?php echo $block->getPagerHtml() ?>
            </div>
        </div>
    </div>
<?php endif;?>
