<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$storeurl = $storeManager->getStore()->getBaseUrl();



?>
<div class="product info detailed" style="position: relative;">
<?php if ($detailedInfoGroup = $block->getGroupChildNames('detailed_info', 'getChildHtml')):?>
    <div class="product-info-detailed" style="float: right; width: 35%;">
        <?php $layout = $block->getLayout(); ?>
        <?php foreach ($detailedInfoGroup as $name):?>
                    <?php
                    $alias = $layout->getElementAlias($name);
                    $label = $block->getChildData($alias, 'title');
                    ?>

<button class="accordion"><?php echo $label; ?></button>

<?php
                $html = $layout->renderElement($name);
                if (!trim($html)) {
                    continue;
                }
                ?>
                <div class="panel">
                  <p><?php echo $html; ?></p>
                </div>

 <?php endforeach;?>    
    </div>
<?php endif; ?>
</div>

<div id="popup-modal-custom" style="display: none;">
<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('size-guide')->toHtml() ?>
</div>

<script>
    require([
        'jquery',
        'Magento_Ui/js/modal/modal'
    ], function ($, modal) {
        var price = $(".price").html();
         setTimeout(function(){ $(".price").html(price+'  <i class="gst"> INCL GST </i>'); }, 3000);

         var html = $('.product-social-links').find('a.mailto').clone().get(0);

         var emailtofriend = '<button class="accordion">Send to a Friend</button>';
         emailtofriend += '<div class="panel"><a class="referfriend" href="'+html+'">Send to a Friend</a></div>'; 
         $('.product-info-detailed').append(emailtofriend);

         var sizeguidehtml = "<?php echo $storeurl; ?>size-guide";
         var sizeguide = '<button class="accordion">Size Guide</button>';
         sizeguide += '<div class="panel"><a class="referfriend" id="opensizeguide" href="#">Size Guide</a></div>';
         $('.product-info-detailed').append(sizeguide);

         

         var acc = document.getElementsByClassName("accordion");
            var i;

            for (i = 0; i < acc.length; i++) {
                acc[i].onclick = function(){
                    this.classList.toggle("active");
                    var panel = this.nextElementSibling;
                    if (panel.style.display === "block") {
                        panel.style.display = "none";
                    } else {
                        panel.style.display = "block";
                    }
                }
            }

            var options = {
                'type': 'popup',
                'modalClass': 'your_popup_custom_class',
                'responsive': true,
                'innerScroll': true,
                'buttons': [{
                    text: $.mage.__('Close'),
                    class: 'back_button_class',
                    click: function () {
                        this.closeModal();
                        // any javascript coode
                    }
                }]
            };  

            var popup = modal(options, $('#popup-modal-custom'));
            $("#opensizeguide").on('click',function(){
                $("#popup-modal-custom").modal("openModal");
            });

    });
</script>

<style>
button.accordion {
    background-color: #eee;
    color: #444;
    cursor: pointer;
    padding: 18px;
    width: 100%;
    border: none;
    text-align: left;
    outline: none;
    font-size: 15px;
    transition: 0.4s;
}

button.accordion.active, button.accordion:hover {
    background-color: #ddd; 
}

div.panel {
    padding: 0 18px;
    display: none;
    background-color: white;
}
</style>