<?php 
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$storeurl = $storeManager->getStore()->getBaseUrl();
?>

<!-- <a href="<?php echo $this->getUrl('customer/account'); ?>" class="side-navbar-btn--link"><span></span></a> -->
<button class="custommyaccountb" >
    <span class="side-navbar-btn topBarIcon sign_in"></span>
</button>

<div class="custom_myaccount hideus" style="display:none;">
    <ul>
        <li><a href="<?php echo $storeurl; ?>customer/account/">My Account</a></li>
        <li><a href="<?php echo $storeurl; ?>sales/order/history/">Track Orders</a></li>
        <li><a href="<?php echo $storeurl; ?>customer/account/logout">Logout</a></li>
    </ul>
</div>


<script>
    require([
        'jquery',
    ], function ($) {
        $("#mobile-switcher-currency-trigger").on('click',function(){
            $(".custom_search").removeClass("active").hide();
            $(".custom_myaccount").removeClass("active").hide();

        });

        $("#mobile-switcher-language-trigger").on('click',function(){
            $(".custom_search").removeClass("active").hide();
            $(".custom_myaccount").removeClass("active").hide();

        });
        $(".action.showcart.topBarIcon").on('click',function(){
            $(".custom_search").removeClass("active").hide();
            $(".custom_myaccount").removeClass("active").hide();

        });

        $(".custommyaccountb").on('click',function(){
            $(".custom_search").removeClass("active").hide();
            $(".custom_login").removeClass("active").hide();

            if($(".custom_myaccount").hasClass("active")){
                $(".custom_myaccount").removeClass("active").hide();
            } else {
                $(".custom_myaccount").addClass("active").show();
            }
            
        });

    });
</script>