<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('contact-us')->toHtml() ?>
</div>
</div>
<div class="grey-bg">
<div class="container">
<div class="contact-form">
<form class="form contact"
      action="<?php /* @escapeNotVerified */ echo $block->getFormAction(); ?>"id="contact-form" method="post"data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>"
      data-mage-init='{"validation":{}}'>
    <fieldset class="fieldset">
        <legend class="legend"><span><?php /* @escapeNotVerified */ //echo __('Write Us') ?></span></legend>        
        <div class="row">
            <div class="field name required col-sm-6 col-xs-12">
                <!--<label class="label" for="name"><span><?php /* @escapeNotVerified */ //echo __('First Name') ?></span></label>-->
                <div class="control">
                    <input name="name" id="name" title="<?php /* @escapeNotVerified */ echo __('First Name') ?>" value="<?php echo $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getUserName()) ?>" placeholder="First Name" class="input-text" type="text" data-validate="{required:true}"/>
                </div>
            </div>
            <div class="field name required col-sm-6 col-xs-12">
                <!--<label class="label" for="name"><span><?php /* @escapeNotVerified */ //echo __('Last Name') ?></span></label>-->
                <div class="control">
                    <input name="" id="name" title="<?php /* @escapeNotVerified */ echo __('Last Name') ?>" placeholder="Last Name" value="" class="input-text" type="text" data-validate="{required:true}"/>
                </div>
            </div>
            <div class="field email required col-sm-6 col-xs-12">
                <!--<label class="label" for="email"><span><?php /* @escapeNotVerified */ //echo __('Email') ?></span></label>-->
                <div class="control">
                    <input name="email" id="email" title="<?php /* @escapeNotVerified */ echo __('Email') ?>" value="<?php echo $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getUserEmail()) ?>" class="input-text" type="email" placeholder="Email" data-validate="{required:true, 'validate-email':true}"/>
                </div>
            </div>
            <div class="field telephone col-sm-6 col-xs-12">
                <!--<label class="label" for="telephone"><span><?php /* @escapeNotVerified */ //echo __('Phone Number') ?></span></label>-->
                <div class="control">
                    <input name="telephone" id="telephone" title="<?php /* @escapeNotVerified */ echo __('Phone Number') ?>" value="" placeholder="Phone Number" class="input-text" type="text" />
                </div>
            </div>
        </div>
        <div class="field comment required">
            <!--<label class="label" for="comment"><span><?php /* @escapeNotVerified */ //echo __('What’s on your mind?') ?></span></label>-->
            <div class="control">
                <textarea placeholder="Message" name="comment" id="comment" title="<?php /* @escapeNotVerified */ echo __('What’s on your mind?') ?>" class="input-text" cols="5" rows="3" data-validate="{required:true}"></textarea>
            </div>
        </div>
        <?php echo $block->getChildHtml('form.additional.info'); ?>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <input type="hidden" name="hideit" id="hideit" value="" />
            <button type="submit" title="<?php /* @escapeNotVerified */ echo __('SEND') ?>" class="action submit primary">
                <span><?php /* @escapeNotVerified */ echo __('SEND') ?></span>
            </button>
        </div>
    </div>
</form>
</div>
</div>