<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Template for displaying new products widget
 *
 * @var $block \Magento\Catalog\Block\Product\Widget\NewWidget
 */
if ($exist = ($block->getProductCollection() && $block->getProductCollection()->getSize())) {
    $type = 'widget-new-grid';

    $mode = 'grid';

    $image = 'new_products_content_widget_grid';
    $title = __('New Products');
    $items = $block->getProductCollection()->getItems();

    $showWishlist = true;
    $showCompare = true;
    $showCart = true;
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::DEFAULT_VIEW;
    $description = true;
}
?>

<?php if ($exist):?>
    <div class="block widget block-new-products <?php /* @escapeNotVerified */ echo $mode; ?>">
        <div class="container">
            <div class="block-title">
                <strong role="heading" aria-level="2"><?php /* @escapeNotVerified */
                    echo $title; ?></strong>
            </div>
            <div class="block-content product-showcasing-slider">
                <?php /* @escapeNotVerified */
                echo '<!-- ' . $image . '-->' ?>
                <div class="products-<?php /* @escapeNotVerified */
                echo $mode; ?> <?php /* @escapeNotVerified */
                echo $mode; ?>">
                    <ol class="product-items <?php /* @escapeNotVerified */
                    echo $type; ?>">
                        <?php $iterator = 1; ?>
                        <?php foreach ($items as $_item): ?>
                            <?php /* @escapeNotVerified */
                            echo ($iterator++ == 1) ? '<li class="product-item">' : '</li><li class="product-item">' ?>
                            <div class="product-item-info">
                                <a href="<?php /* @escapeNotVerified */
                                echo $block->getProductUrl($_item) ?>" class="product-item-photo">
                                    <?php echo $block->getImage($_item, $image)->toHtml(); ?>
                                </a>
                                <div class="product-item-details">
									<div class="detailsCont">
										<div class="detailsInner">
											<strong class="product-item-name">
												<a title="<?php echo $block->escapeHtml($_item->getName()) ?>"
												   href="<?php /* @escapeNotVerified */
												   echo $block->getProductUrl($_item) ?>"
												   class="product-item-link">
													<?php echo $block->escapeHtml($_item->getName()) ?>
												</a>
											</strong>
											<p class="product-small-desc">
												<?php $data = $_item->getDescription();
                                                echo implode(' ', array_slice(str_word_count($data, 2), 0, 5));
                                                ?>
											</p>

											<?php echo $block->getProductPriceHtml($_item, $type)."<i class='gst'> INCL GST </i>";  ?>

											<?php if ($templateType): ?>
												<?php echo $block->getReviewsSummaryHtml($_item, $templateType) ?>
											<?php endif; ?>

											<a href="<?php echo $block->getProductUrl($_item) ?>" class="shopNowBtn lined">Shop Now</a>
										</div>
									</div>
                                </div>
                            </div>
                            <?php echo ($iterator == count($items) + 1) ? '</li>' : '' ?>
                        <?php endforeach ?>
                    </ol>
                </div>
                <?php echo $block->getPagerHtml() ?>
            </div>
        </div>
    </div>
<?php endif;?>
