<?php
/**
 * @copyright   Copyright (c) http://www.manadev.com
 * @license     http://www.manadev.com/license  Proprietary License
 */
/** @var $block \Manadev\LayeredNavigation\Blocks\FilterRenderer */
/** @var $data array */
/** @var $engineFilter \Manadev\LayeredNavigation\EngineFilter */
/** @var $filter \Manadev\LayeredNavigation\Models\Filter */
?>
<ol class="items dsfd" data-mage-init='{ "Manadev_LayeredNavigation/js/FilterView": {} }'>
    <?php foreach ($data as $item): ?>
        <?php if ($item['count'] > 0) : ?>
            <li class="<?php echo $item['is_selected'] ? 'mana-selected' : '' ?> item">
                <a href="<?php echo $block->getReplaceItemUrl($engineFilter, $item) ?>"<?php echo $block->getReplaceItemLinkAttributes($engineFilter, $item) ?>>
				<!--em class="checkbox-empty"></em-->
                    <?php echo $block->escapeItemLabel($engineFilter, $item['label']) ?>
                    <?php if ($block->shouldDisplayProductCountOnLayer()): ?>
                        <span class="count"><?php echo $item['count'] ?><span class="filter-count-label">
                            <?php if ($item['count'] == 1):?>
                                <?php echo __('item')?>
                            <?php else : ?>
                                <?php echo __('items') ?>
                            <?php endif;?>
                        </span></span>
                    <?php endif; ?>
                </a>
            </li>
        <?php else : ?>
            <li class="item">
                <?php echo $block->escapeItemLabel($engineFilter, $item['label']) ?>
                <?php if ($block->shouldDisplayProductCountOnLayer()): ?>
                        <span class="count"><?php echo $item['count'] ?><span class="filter-count-label">
                            <?php if ($item['count'] == 1):?>
                                <?php echo __('item')?>
                            <?php else : ?>
                                <?php echo __('items') ?>
                            <?php endif;?>
                        </span></span>
                <?php endif; ?>
            </li>
        <?php endif; ?>
    <?php endforeach ?>
</ol>
<script>
    require([
        'jquery'
    ], function ($) {
        $('#narrow-by-list ol.items li a').on('click', function(){
            if($(this).find('em').attr('class') === 'checkbox-fil'){
                $(this).find('em').removeClass().addClass("checkbox-empty");
            }else{
                $(this).find('em').removeClass().addClass("checkbox-fil");
            }
        });

    });
</script>
