<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * @var \Magento\Theme\Block\Html\Header\Logo $block
 */
?>
<?php $storeName = $block->getThemeName() ? $block->getThemeName() : $block->getLogoAlt();?>
<?php if ($block->isHomePage()):?>
    <!-- <strong class="logo"> -->
    <a class="logo" href="<?php echo $block->getUrl(''); ?>" title="<?php echo $storeName ?>">
<?php else: ?>
    <a class="logo" href="<?php echo $block->getUrl(''); ?>" title="<?php echo $storeName ?>">
<?php endif ?>
        <img src="<?php echo $block->getLogoSrc() ?>"
             alt="<?php echo $block->getLogoAlt() ?>"
             <?php echo $block->getLogoWidth() ? 'width="' . $block->getLogoWidth() . '"' : '' ?>
             <?php echo $block->getLogoHeight() ? 'height="' . $block->getLogoHeight() . '"' : '' ?>
        />
<?php if ($block->isHomePage()):?>
    <!-- </strong> -->
    </a>
<?php else:?>
    </a>
<?php endif?>


<?php 

$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$customerSession = $objectManager->get('Magento\Customer\Model\Session');
if($customerSession->isLoggedIn()) { ?>
<style type="text/css">
.side-navbar-box.side-navbar-menu {
   display: block !important;
}
.side-navbar-box.side-navbar-login {
  display: none;
  }
</style>

<?php } else { ?>


<?php } ?>
