<?php
$_brandCollection       = $block->getBrandCollection();
$_helper                = $this->helper('Ves\Brand\Helper\Data');
$title                  = $this->getConfig('widget_title');
$show_brand_name        = $this->getConfig('show_brand_name');
?>


<div class="col-md-12 footer-brands">
	<div class="brands-inner">
		<h2><?php echo $title ?></h2>
		<div class="brands-link-container">
		<ul>
				<?php foreach ($_brandCollection as $_brand) { ?>
				<li class="item">
					<?php if($show_brand_name){ ?>
						<a href="<?php echo $_brand->getUrl(); ?>" title="<?php echo $_brand->getName(); ?>"><?php echo $_brand->getName() ?></a>
					<?php } ?>
				</li>
				<?php } ?>
		</ul>
</div>
</div>
</div>


